app:
  host: 127.0.0.1
  port: 5000
  debug: true

database:
  path: local_database.db

logging:
  level: INFO
  path: app/logs/app.log

tradingview:
  base_url: "https://www.tradingview.com/chart/"

