app:
  host: 127.0.0.1
  port: 5000
  debug: true

database:
  signal_path: app/local_database.db
  market_data_path: app/market_data.db
  backtest_path: app/backtest.db

logging:
  level: INFO
  path: app/logs/app.log

tradingview:
  base_url: "https://www.tradingview.com/chart/"

